INSERT INTO PHONG(ID_NHA,TEN_PHONG,ID_LOAIPHONG,ID_LOAIGIUONG,SOGIUONG,SONGUOITOIDA,SOGIUONG_PHU,CHIEUDAI_PHONG,CHIEURONG_PHONG,SOLUONG,MOTA)
VALUES
('BIETTHU0215',N'Phòng chính',2,5,1,2,0,12,12,1,N'Phòng chung cho 2 người'),
('BIETTHU0215',N'Phòng phụ',2,1,1,1,0,12,12,1,N'Phòng chung cho 1 người');