--TAI KHOAN
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('Chung','dsadanca@33!','Customer')--1
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('tuan123','tuantuan','Customer')--1
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('thanh123','thanhpp','Partner')--2
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('nha123','nhathanh','Partner')--3
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('lien123','nguyenlien223','Admin')--4 KHONG CO THONG TIN ?????
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('huy123','huychan','Customer')--5

--THONG TIN KHACH HANG
INSERT THONGTINKHACHHANG(TEN_KHACHHANG,EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,LOAI_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,ID_TAIKHOAN) 
VALUES ('Lam Tuan','tuan123@gmail','0901119999','033266565656','Chứng minh nhân dân','Viet nam', 0, 0)

INSERT THONGTINKHACHHANG(TEN_KHACHHANG,EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,LOAI_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,ID_TAIKHOAN) 
VALUES ('Viet Huy','huy123@gmail','0901119999','Hộ chiếu','1','VietNam', 0, 6)

--THONG TIN CHU HO (XEM LAI MASO_THUE)!!!!!!
INSERT THONGTINCHUHO(TEN_CHUHO,EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,LOAI_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,DIACHI,MASO_THUE,ID_TAIKHOAN) 
VALUES ('Nguyen Thanh','thanh123@gmail','0901119999','033266565656','Hộ chiếu','Laos',1,N'77 Nguyễn Xuân','158265', 0)

INSERT THONGTINCHUHO(TEN_CHUHO,EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,LOAI_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,DIACHI,MASO_THUE,ID_TAIKHOAN) 
VALUES ('Nhu Nha','nha123@gmail','0901119999','Visa','1','China',1,N'12/5/54 Nguyễn Huệ','203524', 4)

