INSERT INTO TRANGTHAINHA(TEN_TRANGTHAI)
VALUES
(N'Ngừng kinh doanh'),
(N'Đang mở'),
(N'Đang được thuê')

--TRANG THAI DAT CAN HO
INSERT TRANGTHAIDATCANHO(TEN_TRANGTHAI) VALUES ('NEW')
INSERT TRANGTHAIDATCANHO(TEN_TRANGTHAI) VALUES ('ACCEPTED')
INSERT TRANGTHAIDATCANHO(TEN_TRANGTHAI) VALUES ('CANCELED')
INSERT TRANGTHAIDATCANHO(TEN_TRANGTHAI) VALUES ('OVERTIME')