--STYLE
INSERT STYLE(TEN_STYLE) VALUES('CLASSIC')
INSERT STYLE(TEN_STYLE) VALUES('MODERN')
INSERT STYLE(TEN_STYLE) VALUES('NATURE')
INSERT STYLE(TEN_STYLE) VALUES('RICH')

--STYLE NHA
INSERT STYLENHA(ID_NHA, ID_STYLE) VALUES(1,4)
INSERT STYLENHA(ID_NHA, ID_STYLE) VALUES(2,2)