--TAI KHOAN
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('tuan123','tuantuan','Customer')
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('thanh123','thanhpp','Partner')
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('nha123','nhathanh','Partner')
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('lien123','nguyenlien223','Admin')
INSERT TAIKHOAN(TEN_TAIKHOAN,MATKHAU, ROLE_TAIKHOAN) VALUES ('huy123','huychan','Customer')
--THONG TIN KHACH HANG
INSERT THONGTINKHACHHANG(EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,ID_TAIKHOAN) 
VALUES ('tuan123@gmail','0901119999','Chứng minh nhân dân','Viet nam', 0, 1)

INSERT THONGTINKHACHHANG(EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,ID_TAIKHOAN) 
VALUES ('thanh123@gmail','0901119999','Căn cước công dân','Laos', 1, 2)

INSERT THONGTINKHACHHANG(EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,ID_TAIKHOAN) 
VALUES ('nha123@gmail','0901119999','Căn cước công dân','China', 1, 3)

INSERT THONGTINKHACHHANG(EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,ID_TAIKHOAN) 
VALUES ('lien123@gmail','0901119999','Visa','Campuchia', 1, 4)

INSERT THONGTINKHACHHANG(EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,ID_TAIKHOAN) 
VALUES ('huy123@gmail','0901119999','Hộ chiếu','VietNam', 0, 5)
--THONG TIN CHU HO
INSERT THONGTINCHUHO(ID_TT_CHUHO,EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,LOAI_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,DIACHI,ID_TAIKHOAN) 
VALUES ('thanh123@gmail','0901119999','Hộ chiếu','1','Laos',1,N'77 Nguyễn Xuân, Thanh Mai, Hà Nội ', 2)

INSERT THONGTINCHUHO(ID_TT_CHUHO,EMAIL,PHONE_NUMBER, MA_GIAYTOTUYTHAN,LOAI_GIAYTOTUYTHAN,QUOCTICH,GIOITINH,DIACHI,ID_TAIKHOAN) 
VALUES (2,'nha123@gmail','0901119999','Visa','1','China',1,N'12/5/54 Nguyễn Huệ, quận 12, TPHCM', 3)

--DANH GIA
INSERT DANHGIA(ID_DANHGIA,ID_NHA, SOSAO,NOIDUNG) 
VALUES (1,5,1,'5','It pretty medium')

--TRANG THAI DAT CAN HO
INSERT TRANGTHAIDATCANHO(ID_TT_DCH,TEN_TRANGTHAI) VALUES (1,'AVAILABLE')
INSERT TRANGTHAIDATCANHO(ID_TT_DCH,TEN_TRANGTHAI) VALUES (2,'UNAVAILABLE')